version: '3.9'
services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: trendsnap
      POSTGRES_PASSWORD: trendsnap
      POSTGRES_DB: trendsnap
    ports:
      - '5432:5432'
  app:
    build: .
    ports:
      - '3000:3000'
    volumes:
      - .:/app
    depends_on:
      - db
