name: CI
on:
  pull_request:
  push:
    tags:
      - 'v*'
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - uses: yarnpkg/berry-setup-action@master
      - run: yarn install --immutable
      - run: yarn test
  release:
    if: startsWith(github.ref, 'refs/tags/')
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Draft release
        uses: softprops/action-gh-release@v1
        with:
          draft: true
          files: docs/api.html
          body_path: CHANGELOG.md
          name: TrendSnap ${{ github.ref_name }}
